# -*- coding: utf-8 -*-
"""radioblip_ver6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bH-j7QH-3l0rAGEKjGETmayqN4TrnH9H
"""



# ─────────────────────────────────────────────────────────────
# 1.  IMPORTS
# ─────────────────────────────────────────────────────────────
import ast
import os
import re
import random
import math
from collections import defaultdict

import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

from transformers import (
    AutoTokenizer,
    AutoModel,
    AutoFeatureExtractor,
    AutoImageProcessor,
    AutoModelForCausalLM,
    Blip2ForConditionalGeneration,
    get_cosine_schedule_with_warmup,
)
from tqdm import tqdm

import torch.nn.functional as F

# ─────────────────────────────────────────────────────────────
# 2.  DATA LOADING & PREPROCESSING
# ─────────────────────────────────────────────────────────────

def load_and_expand_dataframe(csv_path: str) -> pd.DataFrame:
    """
    Reads the raw MIMIC-CXR CSV, expands each row (which contains
    lists of image paths and reports) into one row per study,
    and concatenates the augmented text onto the base report.
    """
    df = pd.read_csv(csv_path)

    # Parse stringified lists
    df["image_list"]    = df["image"].apply(ast.literal_eval)
    df["text_list"]     = df["text"].apply(ast.literal_eval)
    df["text_aug_list"] = df["text_augment"].apply(ast.literal_eval)

    def extract_study_id(path: str):
        match = re.search(r'/s(\d+)/', path)
        return match.group(1) if match else None

    expanded_rows = []

    for _, row in df.iterrows():
        study_ids     = [extract_study_id(p) for p in row["image_list"]]
        unique_studies = list(dict.fromkeys(study_ids))   # preserve order

        study_groups: dict = defaultdict(list)
        for path in row["image_list"]:
            sid = extract_study_id(path)
            study_groups[sid].append(path)

        for idx, study_id in enumerate(unique_studies):
            if idx >= len(row["text_list"]):
                continue   # safety guard

            report = row["text_list"][idx]
            if idx < len(row["text_aug_list"]):
                report += " " + row["text_aug_list"][idx]

            expanded_rows.append({
                "subject_id": row["subject_id"],
                "study_id":   study_id,
                "images":     study_groups[study_id],
                "report":     report,
            })

    return pd.DataFrame(expanded_rows)

# ─────────────────────────────────────────────────────────────
# 3.  DATASET
# ─────────────────────────────────────────────────────────────

PROMPT = "Chest X-ray Report:\nFindings:\n"

class MIMICCXRDataset(Dataset):

    def __init__(
        self,
        df: pd.DataFrame,
        root_dir: str,
        tokenizer_name: str = "microsoft/biogpt",
        max_length: int = 256,
    ):
        self.df          = df.reset_index(drop=True)
        self.root_dir    = root_dir
        self.max_length  = max_length
        self.tokenizer   = AutoTokenizer.from_pretrained(tokenizer_name)

        
        self.valid_indices = self._filter_valid_indices()
 
        self.processor = AutoImageProcessor.from_pretrained(
            "microsoft/rad-dino"
        )

    def _filter_valid_indices(self):
        """Pre-filter rows whose images actually exist on disk."""
        valid = []
        for i, row in self.df.iterrows():
            all_exist = all(
                os.path.exists(os.path.join(self.root_dir, p))
                for p in row["images"]
            )
            if all_exist:
                valid.append(i)
        print(f"[Dataset] {len(valid)} / {len(self.df)} studies have all images on disk.")
        return valid

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        row = self.df.iloc[self.valid_indices[idx]]

        # ── Images ──────────────────────────────────────────
        pil_images = []
        for path in row["images"]:
            full_path = os.path.join(self.root_dir, path)
            pil_images.append(Image.open(full_path).convert("RGB"))

        # processor returns pixel_values: [N, 3, 518, 518]
        images = self.processor(
            images=pil_images,
            return_tensors="pt",
        )["pixel_values"]                      # [N, 3, 518, 518]

        # ── Tokenise ─────────────────────────────────────────
        #   Tokenising PROMPT separately so we can mask it in labels.
        prompt_ids = self.tokenizer(
            PROMPT, add_special_tokens=False
        )["input_ids"]
        prompt_len = len(prompt_ids)

        full_text = PROMPT + row["report"]
        encoding  = self.tokenizer(
            full_text,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt",
        )

        input_ids      = encoding["input_ids"].squeeze(0)
        attention_mask = encoding["attention_mask"].squeeze(0)

         
        labels = input_ids.clone()
        labels[attention_mask == 0]       = -100   # padding
        labels[:prompt_len]               = -100   # prompt prefix

        return {
            "images":         images,
            "input_ids":      input_ids,
            "attention_mask": attention_mask,
            "labels":         labels,
        }

# ─────────────────────────────────────────────────────────────
# 4.  COLLATE FUNCTION
# ─────────────────────────────────────────────────────────────

def collate_fn(batch):
    max_imgs = max(item["images"].shape[0] for item in batch)

    padded_images = []
    image_masks   = []

    for item in batch:
        imgs = item["images"]
        n    = imgs.shape[0]
        pad  = torch.zeros(max_imgs - n, *imgs.shape[1:])

        padded_images.append(torch.cat([imgs, pad], dim=0))
        image_masks.append(
            torch.cat([torch.ones(n), torch.zeros(max_imgs - n)])
        )

    return {
        "images":         torch.stack(padded_images),          # [B, N, 3, 224, 224]
        "image_mask":     torch.stack(image_masks),            # [B, N]
        "input_ids":      torch.stack([b["input_ids"]      for b in batch]),
        "attention_mask": torch.stack([b["attention_mask"] for b in batch]),
        "labels":         torch.stack([b["labels"]         for b in batch]),
    }

# ─────────────────────────────────────────────────────────────
# 5.  MODEL
# ─────────────────────────────────────────────────────────────

class VisionEncoder(nn.Module):
    def __init__(self, freeze: bool = True):
        super().__init__()
       
        self.model = AutoModel.from_pretrained("microsoft/rad-dino")
        if freeze:
            for p in self.model.parameters():
                p.requires_grad = False

    def forward(self, x):
        
        return self.model(pixel_values=x).last_hidden_state  # [B, 257, 768]

    @property
    def num_features(self):
        return self.model.config.hidden_size   # 768


class RadBLIPBioGPT(nn.Module):

    def __init__(
        self,
        biogpt_name: str    = "microsoft/biogpt",
        num_query_tokens: int = 32,
    ):
        super().__init__()

        # ── Vision Encoder ────────────────────────────────────
        self.vision_encoder = VisionEncoder(freeze=True)
        vision_dim = self.vision_encoder.num_features          # 768 (Rad-DINO)

        # ── Q-Former ──────────────────────────────────────────

        # Using BLIP-2 OPT-2.7B: its Q-Former was trained to interface with
        # a decoder-only LLM (OPT), which matches BioGPT's causal LM architecture.
        blip2_model = Blip2ForConditionalGeneration.from_pretrained(
            "Salesforce/blip2-opt-2.7b"
        )
        self.qformer = blip2_model.qformer
        # Reinitialize query tokens with BERT-style init so they start
        # neutral and learn CXR-specific visual summarization from scratch,
        # while the Q-Former transformer weights (pretrained on 129M pairs)
        # are preserved for their learned cross-attention mechanics.
        self.qformer.query_tokens = nn.Parameter(
            torch.zeros(1, num_query_tokens, self.qformer.config.hidden_size)
        )
        nn.init.trunc_normal_(self.qformer.query_tokens, std=0.02)
        self.num_query_tokens = num_query_tokens

        # ── Vision → Q-Former projection ──────────────────────
 
        self.vision_proj = nn.Linear(vision_dim, qformer_vis_dim)

        # ── BioGPT ────────────────────────────────────────────
        self.llm = AutoModelForCausalLM.from_pretrained(biogpt_name)
        for p in self.llm.parameters():
            p.requires_grad = False

        llm_hidden = self.llm.config.hidden_size

        # ── Q-Former → BioGPT projection ──────────────────────
        self.proj = nn.Linear(self.qformer.config.hidden_size, llm_hidden)

    # ──────────────────────────────────────────────────────────
    def forward(
        self,
        images,           # [B, N, 3, 224, 224]
        image_mask,       # [B, N]
        input_ids,
        attention_mask,
        labels,
    ):
        B, N, C, H, W = images.shape

        # ── 1. Encode images ──────────────────────────────────
        image_embeds = self.vision_encoder(images.view(B * N, C, H, W))  # [B*N, 197, 768]
        image_embeds = self.vision_proj(image_embeds)                     # [B*N, 197, 1024]
        T, D = image_embeds.shape[1], image_embeds.shape[2]
        image_embeds = image_embeds.view(B, N, T, D)

        # ── 2. Fuse valid images per study ────────────────────
        fused_tokens = []
        for i in range(B):
            valid = image_embeds[i][image_mask[i].bool()]   # [n_i, T, D]  i.e. [#images, #token, dim_token]
            fused_tokens.append(valid.reshape(-1, D))        # [n_i*T, D]  and the concatenated vector is [image1_tokens || image2_tokens || ...imageN_tokens] i.e. fusion along token dimension

        # ── 3. Pad across batch for Q-Former ──────────────────
        max_tokens = max(t.shape[0] for t in fused_tokens)
        padded_visuals, visual_att_mask = [], []

        for t in fused_tokens:
            pad_len = max_tokens - t.shape[0]
            padded  = torch.cat([
                t,
                torch.zeros(pad_len, D, device=t.device, dtype=t.dtype)
            ], dim=0)
            mask = torch.cat([
                torch.ones(t.shape[0],  device=t.device),
                torch.zeros(pad_len,    device=t.device),
            ])
            padded_visuals.append(padded)
            visual_att_mask.append(mask)

        image_embeds       = torch.stack(padded_visuals)    # [B, max_T, D]
        visual_att_mask    = torch.stack(visual_att_mask)   # [B, max_T]

        # ── 4. Q-Former ───────────────────────────────────────
        query_tokens = self.qformer.query_tokens.expand(B, -1, -1)
        q_out = self.qformer(
            query_embeds=query_tokens,
            encoder_hidden_states=image_embeds,
            encoder_attention_mask=visual_att_mask,
            return_dict=True,
        )
        visual_tokens = self.proj(q_out.last_hidden_state)  # [B, Q, llm_h]

        # ── 5. Prepend visual tokens to text embeddings ───────
        text_embeds    = self.llm.get_input_embeddings()(input_ids)
        inputs_embeds  = torch.cat([visual_tokens, text_embeds], dim=1)

        vis_prefix_mask = torch.ones(
            B, visual_tokens.size(1),
            device=attention_mask.device, dtype=attention_mask.dtype,
        )
        full_attention_mask = torch.cat([vis_prefix_mask, attention_mask], dim=1)

        vis_labels  = torch.full(
            (B, visual_tokens.size(1)), -100,                           # visual labels are masked out
            device=labels.device, dtype=labels.dtype,
        )
        full_labels = torch.cat([vis_labels, labels], dim=1)

        # ── 6. BioGPT forward ────────────────────────────────
        outputs = self.llm(
            inputs_embeds=inputs_embeds,
            attention_mask=full_attention_mask,
            labels=full_labels,
            return_dict=True,
        )
        return outputs.loss

# ─────────────────────────────────────────────────────────────
# 6.  FREEZE / UNFREEZE HELPERS
# ─────────────────────────────────────────────────────────────

def freeze_module(module: nn.Module):
    for p in module.parameters():
        p.requires_grad = False

def unfreeze_module(module: nn.Module):
    for p in module.parameters():
        p.requires_grad = True

def unfreeze_last_n_layers_biogpt(model: RadBLIPBioGPT, n_layers: int = 2):
    freeze_module(model.llm)
    total = len(model.llm.biogpt.layers)
    for i in range(total - n_layers, total):
        for p in model.llm.biogpt.layers[i].parameters():
            p.requires_grad = True
    print(f"[Unfreeze] Last {n_layers} / {total} BioGPT layers are now trainable.")

# ─────────────────────────────────────────────────────────────
# 7.  EARLY STOPPING
# ─────────────────────────────────────────────────────────────

class EarlyStopping:
    def __init__(self, patience: int = 3, min_delta: float = 1e-4):
        self.patience  = patience
        self.min_delta = min_delta
        self.best_loss = float("inf")
        self.counter   = 0

    def step(self, val_loss: float) -> bool:
        """Returns True if training should stop."""
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss = val_loss
            self.counter   = 0
            return False
        self.counter += 1
        print(f"[EarlyStopping] No improvement for {self.counter} / {self.patience} epoch(s).")
        return self.counter >= self.patience

def train_stage(
    model: nn.Module,
    loader: DataLoader,
    optimizer: torch.optim.Optimizer,
    epochs: int,
    start_epoch: int = 1,
    scheduler_state: dict | None = None,
    device: str="cuda" if torch.cuda.is_available() else "cpu",
    stage_name: str          = "stage",
    max_grad_norm: float     = 0.5,
    warmup_ratio: float      = 0.2,
    save_dir: str            = "checkpoints",
    early_stopper: EarlyStopping | None = None,
    accumulation_steps: int  = 1,           
):
    os.makedirs(save_dir, exist_ok=True)

    scaler = torch.amp.GradScaler("cuda", init_scale=1024)

    
    total_steps  = (len(loader) // accumulation_steps) * epochs
    warmup_steps = max(1, int(total_steps * warmup_ratio))
    scheduler    = get_cosine_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=total_steps,
    )
    if scheduler_state is not None:
        scheduler.load_state_dict(scheduler_state)

    best_loss = float("inf")


    for epoch in range(start_epoch, epochs + 1):
        model.train()
        epoch_loss  = 0.0
        num_batches = 0

        loop = tqdm(loader, desc=f"[{stage_name}] Epoch {epoch}/{epochs}", leave=False)
        optimizer.zero_grad()                  # zero once before the epoch

        for i, batch in enumerate(loop):
            images         = batch["images"].to(device)
            image_mask     = batch["image_mask"].to(device)
            input_ids      = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels         = batch["labels"].to(device)

            with torch.amp.autocast("cuda"):
                loss = model(
                    images=images,
                    image_mask=image_mask,
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    labels=labels,
                )
                loss = loss / accumulation_steps   # normalize so scale stays correct

            scaler.scale(loss).backward()          # gradients accumulate here

            # Only step every `accumulation_steps` batches
            if (i + 1) % accumulation_steps == 0:
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(
                    filter(lambda p: p.requires_grad, model.parameters()),
                    max_grad_norm,
                )
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()               
                scheduler.step()

            loss_val     = loss.item() * accumulation_steps   # un-normalize for display
            epoch_loss  += loss_val
            num_batches += 1

            loop.set_postfix(
                loss=f"{loss_val:.4f}",
                lr=f"{scheduler.get_last_lr()[0]:.2e}",
            )

        mean_loss = epoch_loss / max(num_batches, 1)
           # After epoch ends, print one clean summary line
        tqdm.write(
            f"[{stage_name}] Epoch {epoch}/{epochs}  "
            f"mean_loss={mean_loss:.4f}  "
            f"lr={scheduler.get_last_lr()[0]:.2e}"
        )

        if mean_loss < best_loss:
            best_loss = mean_loss
            ckpt_path = os.path.join(save_dir, f"{stage_name}_best.pt")
            torch.save({
                "epoch":      epoch,
                "model":      model.state_dict(),
                "optimizer":  optimizer.state_dict(),
                "scheduler":  scheduler.state_dict(),
                "loss":       best_loss,
            }, ckpt_path)
            tqdm.write(f"  ↳ New best ({best_loss:.4f}) — checkpoint saved → {ckpt_path}")

        if epoch % 2 == 0:
            periodic_path = os.path.join(save_dir, f"{stage_name}_epoch{epoch}.pt")
            torch.save(model.state_dict(), periodic_path)

        if early_stopper is not None and early_stopper.step(mean_loss):
            print(f"[{stage_name}] Early stopping triggered at epoch {epoch}.")
            break

import os

# ─────────────────────────────────────────────────────────────
# STAGE 0 — Q-FORMER PRETRAINING  (qformer_pretrain_v2.py)
# It is run before Stage 1 to warm-start the Q-Former with ITC + ITM + IGT objectives on the MIMIC-CXR dataset.
# ─────────────────────────────────────────────────────────────

from transformers import BertTokenizer, BertModel

# ── 8a.  PRETRAIN DATASET ─────────────────────────────────────

class MIMICCXRPretrainDataset(Dataset):
    """
    Pretraining dataset for Stage 0 Q-Former alignment.

    FIX (normalization): uses BioViL-T's AutoFeatureExtractor instead of
    manual torchvision transforms, so pixel values are normalized with the
    exact same mean/std that the frozen BioViL-T backbone expects.  The
    original Normalize([0.5],[0.5]) caused a distribution mismatch between
    Stage 0 image features and those produced at Stage 1.
    """
    def __init__(self, df, root_dir, max_length=128):
        self.df         = df.reset_index(drop=True)
        self.root_dir   = root_dir
        self.max_length = max_length

        # BERT tokenizer for ITC / ITM text encoding
        self.tokenizer  = BertTokenizer.from_pretrained("bert-base-uncased")
        self.tokenizer.add_special_tokens({"bos_token": "[DEC]"})
        self.dec_token_id = self.tokenizer.convert_tokens_to_ids("[DEC]")

        self.valid_indices = self._filter_valid_indices()
        print(f"[PretrainDataset] {len(self.valid_indices)} / {len(self.df)} valid studies.")

    
        self.processor = AutoImageProcessor.from_pretrained(
            "microsoft/rad-dino"
        )

    def _filter_valid_indices(self):
        valid = []
        for i, row in self.df.iterrows():
            if all(os.path.exists(os.path.join(self.root_dir, p)) for p in row["images"]):
                valid.append(i)
        return valid

    def __len__(self):
        return len(self.valid_indices)

    def __getitem__(self, idx):
        row = self.df.iloc[self.valid_indices[idx]]

        # Load PIL images and let the processor handle resize + normalize
        pil_images = [
            Image.open(os.path.join(self.root_dir, p)).convert("RGB")
            for p in row["images"]
        ]
         
        images = self.processor(images=pil_images, return_tensors="pt")["pixel_values"]

      
        report    = row["report"]
        sentences = report.split(".")
        short_rep = ". ".join(sentences[:2]).strip() + "."

        enc = self.tokenizer(
            short_rep,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt",
        )

        return {
            "images":         images,
            "text_input_ids": enc["input_ids"].squeeze(0),
            "text_attn_mask": enc["attention_mask"].squeeze(0),
        }


def pretrain_collate_fn(batch):
    max_imgs = max(item["images"].shape[0] for item in batch)
    padded_images, image_masks = [], []
    for item in batch:
        imgs = item["images"]
        n    = imgs.shape[0]
        pad  = torch.zeros(max_imgs - n, *imgs.shape[1:])
        padded_images.append(torch.cat([imgs, pad], dim=0))
        image_masks.append(torch.cat([torch.ones(n), torch.zeros(max_imgs - n)]))

    return {
        "images":         torch.stack(padded_images),
        "image_mask":     torch.stack(image_masks),
        "text_input_ids": torch.stack([b["text_input_ids"] for b in batch]),
        "text_attn_mask": torch.stack([b["text_attn_mask"] for b in batch]),
    }

# ── 8b.  ATTENTION MASK GENERATOR ────────────────────────────

def generate_attention_mask(task: str, query_len: int, pad_mask: torch.Tensor, device: str):
    """
    Generates attention mask for the CrossModalTransformer.
    Convention: 0 = can attend, -inf = cannot attend.

    task      : "itc" | "itm" | "igt"
    query_len : number of learnable query tokens Q
    pad_mask  : (B, L) — 1=valid token, 0=padding
    """
    batch_size, text_len = pad_mask.size()
    total_len = query_len + text_len

    task_mask = torch.zeros((batch_size, total_len, total_len), device=device)

    if task == "itm":
        pass  # full attention

    elif task == "igt":
        causal_indices = torch.triu_indices(text_len, text_len, offset=1, device=device)
        for b in range(batch_size):
            task_mask[b,
                      query_len + causal_indices[0],
                      query_len + causal_indices[1]] = float("-inf")
        task_mask[:, :query_len, query_len:] = float("-inf")

    elif task == "itc":
        task_mask[:, :query_len, query_len:] = float("-inf")
        task_mask[:, query_len:, :query_len] = float("-inf")

    padding_positions = (pad_mask == 0)
    for b in range(batch_size):
        if padding_positions[b].any():
            pad_idx = torch.nonzero(padding_positions[b], as_tuple=True)[0]
            task_mask[b, :, query_len + pad_idx] = float("-inf")
            task_mask[b, query_len + pad_idx, :] = float("-inf")

    return task_mask


# ── 8c.  Q-FORMER PRETRAINER ──────────────────────────────────

class QFormerPretrainer(nn.Module):
    """
    Pretrains the Q-Former using ITC + ITM + IGT losses.

    Shares vision_encoder, vision_proj, and qformer with the base
    RadBLIPBioGPT instance, so all gradient updates flow directly into
    the weights that Stage 1 will continue training — no copy needed.

    FIX 2 (IGT vocab): lm_head now projects into BioGPT's vocabulary
    (42,384 tokens) instead of BERT's (30,522 tokens), and the IGT text
    is encoded with BioGPT's tokenizer.  This makes the IGT language
    supervision directly compatible with Stage 1 generation targets.

    FIX 3 (silent mask drop): _run_qformer now passes visual_att_mask as
    encoder_attention_mask so padding in the visual token sequence is
    masked correctly inside the Q-Former cross-attention layers.
    """
    def __init__(self, base_model: RadBLIPBioGPT):
        super().__init__()

        # Shared weights with RadBLIPBioGPT — updates here persist to Stage 1
        self.vision_encoder   = base_model.vision_encoder
        self.vision_proj      = base_model.vision_proj
        self.qformer          = base_model.qformer
        self.num_query_tokens = base_model.num_query_tokens
        qformer_dim           = self.qformer.config.hidden_size   # 768

        # BERT — for ITC / ITM text encoding only
        self.bert_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
        self.bert_tokenizer.add_special_tokens({"bos_token": "[DEC]"})
        self.dec_token_id_bert = self.bert_tokenizer.convert_tokens_to_ids("[DEC]")

        self.bert = BertModel.from_pretrained("bert-base-uncased")
        self.bert.resize_token_embeddings(len(self.bert_tokenizer))
        for p in self.bert.parameters():
            p.requires_grad = False
        for layer in list(self.bert.encoder.layer)[-4:]:
            for p in layer.parameters():
                p.requires_grad = True

        bert_dim = self.bert.config.hidden_size   # 768
 
        self.biogpt_tokenizer = AutoTokenizer.from_pretrained("microsoft/biogpt")
        biogpt_vocab_size     = base_model.llm.config.vocab_size   # 42,384
        # Reuse BioGPT's input embedding layer (frozen) to encode IGT text
        self.biogpt_embed = base_model.llm.get_input_embeddings()
        for p in self.biogpt_embed.parameters():
            p.requires_grad = False
        biogpt_embed_dim = base_model.llm.config.hidden_size       # 1024

        # Project Q-Former dim (768) → BioGPT embed dim (1024) for IGT encoding
        self.igt_proj = nn.Linear(qformer_dim, biogpt_embed_dim)

        # ITC / ITM projections
        self.vision_projection = nn.Linear(qformer_dim, qformer_dim)
        self.text_projection   = nn.Linear(bert_dim,    qformer_dim)
        self.temperature       = nn.Parameter(torch.ones([]) * 0.07)
        self.itm_head          = nn.Linear(qformer_dim, 2)

        # FIX 2: lm_head over BioGPT vocab, preceded by igt_proj
        self.lm_head = nn.Linear(biogpt_embed_dim, biogpt_vocab_size)

        self._init_weights()

    def _init_weights(self):
        for lin in [self.vision_projection, self.text_projection, self.igt_proj]:
            nn.init.kaiming_normal_(lin.weight, nonlinearity="relu")
            nn.init.zeros_(lin.bias)
        for lin in [self.itm_head, self.lm_head]:
            nn.init.normal_(lin.weight, std=0.02)
            nn.init.zeros_(lin.bias)
        nn.init.constant_(self.temperature, 0.07)

    def _encode_images(self, images, image_mask):
        B, N, C, H, W = images.shape
   
        chunks = []
        for b in range(B):
            chunk = self.vision_encoder(images[b])   # [N, H, W] → [N, 257, 768]
            chunk = self.vision_proj(chunk)
            chunks.append(chunk)
        image_embeds = torch.stack(chunks, dim=0)    # [B, N, 257, 768]
        torch.cuda.empty_cache()
        T, D = image_embeds.shape[2], image_embeds.shape[3]
        image_embeds = image_embeds.view(B, N, T, D)

        fused_tokens, visual_att_masks = [], []
        for i in range(B):
            valid = image_embeds[i][image_mask[i].bool()]
            fused_tokens.append(valid.reshape(-1, D))

        max_tokens = max(t.shape[0] for t in fused_tokens)
        padded_visuals, visual_att_mask = [], []
        for t in fused_tokens:
            pad_len = max_tokens - t.shape[0]
            padded  = torch.cat([t, torch.zeros(pad_len, D, device=t.device, dtype=t.dtype)], dim=0)
            mask    = torch.cat([torch.ones(t.shape[0], device=t.device),
                                 torch.zeros(pad_len, device=t.device)])
            padded_visuals.append(padded)
            visual_att_mask.append(mask)

        image_feats = torch.stack(padded_visuals)
        image_feats = F.normalize(image_feats, dim=-1)
        return image_feats, torch.stack(visual_att_mask)   # [B,T,D], [B,T]

    def _encode_text_bert(self, text_input_ids, text_attn_mask):
        return self.bert(
            input_ids=text_input_ids,
            attention_mask=text_attn_mask,
            return_dict=True,
        )

    def _run_qformer(self, image_feats, visual_att_mask, queries):
      
        q_out = self.qformer(
            query_embeds=queries,
            encoder_hidden_states=image_feats,
            encoder_attention_mask=visual_att_mask,   # FIX 3
            return_dict=True,
        )
        return q_out.last_hidden_state   # [B, Q, 768]

    def forward(self, images, image_mask, text_input_ids, text_attn_mask,
                igt_input_ids, igt_attn_mask, igt_labels):
        """
        images          : [B, N, 3, 224, 224]
        image_mask      : [B, N]
        text_input_ids  : [B, L]   BERT tokens for ITC/ITM
        text_attn_mask  : [B, L]
        igt_input_ids   : [B, L2]  BioGPT tokens for IGT
        igt_attn_mask   : [B, L2]
        igt_labels      : [B, L2]  BioGPT token ids, -100 on padding/prefix
        """
        B      = images.shape[0]
        device = images.device

        image_feats, visual_att_mask = self._encode_images(images, image_mask)

        text_output = self._encode_text_bert(text_input_ids, text_attn_mask)
        text_embeds = text_output.last_hidden_state    # [B, L, 768]

        queries = self.qformer.query_tokens.expand(B, -1, -1).clone()
        Q       = queries.shape[1]

        # ── ITC ───────────────────────────────────────────────
        updated_queries_itc = self._run_qformer(image_feats, visual_att_mask, queries)

        queries_itc = F.normalize(self.vision_projection(updated_queries_itc), dim=-1)
        cls_text    = F.normalize(self.text_projection(text_embeds[:, 0, :]),   dim=-1)

        sim_i2t = torch.einsum("bqd, td -> btq", queries_itc, cls_text)
        sim_i2t, _ = sim_i2t.max(dim=-1)
        sim_i2t = sim_i2t / self.temperature
        sim_t2i = sim_i2t.T

        targets  = torch.arange(B, device=device)
        loss_itc = (
            F.cross_entropy(sim_i2t, targets, label_smoothing=0.1) +
            F.cross_entropy(sim_t2i, targets, label_smoothing=0.1)
        ) / 2

        # ── ITM ───────────────────────────────────────────────
        with torch.no_grad():
            sim_i2t_neg = sim_i2t.clone().fill_diagonal_(-10000)
            sim_t2i_neg = sim_t2i.clone().fill_diagonal_(-10000)
            weights_i2t = torch.softmax(sim_i2t_neg, dim=-1)
            weights_t2i = torch.softmax(sim_t2i_neg, dim=-1)

        image_feats_neg = torch.stack([
            image_feats[torch.multinomial(weights_t2i[b], 1).item()] for b in range(B)
        ])
        vis_mask_neg = torch.stack([
            visual_att_mask[torch.multinomial(weights_t2i[b], 1).item()] for b in range(B)
        ])
        text_embeds_neg = torch.stack([
            text_embeds[torch.multinomial(weights_i2t[b], 1).item()] for b in range(B)
        ])

        # 3× batch: [pos, neg-img, neg-txt]
        # Chunked into 3 separate B-sized Q-Former passes to avoid the
        # 3*B×257-token cross-attention OOM that kills Rad-DINO training.
        queries_single    = self.qformer.query_tokens.expand(B, -1, -1).clone()
        q_pos             = self._run_qformer(image_feats,     visual_att_mask, queries_single)
        q_neg_img         = self._run_qformer(image_feats_neg, vis_mask_neg,    queries_single)
        q_neg_txt         = self._run_qformer(image_feats,     visual_att_mask, queries_single)
        updated_queries_itm = torch.cat([q_pos, q_neg_img, q_neg_txt], dim=0)  # [3*B, Q, D]
        torch.cuda.empty_cache()

        itm_logits = self.itm_head(updated_queries_itm).mean(dim=1)
        itm_labels = torch.cat([
            torch.ones(B,  dtype=torch.long, device=device),   # pos
            torch.zeros(B, dtype=torch.long, device=device),   # neg-img
            torch.ones(B,  dtype=torch.long, device=device),   # neg-txt → 1 (image correct)
        ])
        loss_itm = F.cross_entropy(itm_logits, itm_labels)

        # ── IGT ── BioGPT vocab ───────────────────────────────
        # FIX 2: embed IGT tokens with BioGPT's embedding, project Q-Former
        # output to BioGPT's embed dim, then apply lm_head over BioGPT vocab.
        queries_igt = self.qformer.query_tokens.expand(B, -1, -1).clone()
        updated_queries_igt = self._run_qformer(image_feats, visual_att_mask, queries_igt)
        # [B, Q, 768] → [B, Q, 1024]
        projected_queries = self.igt_proj(updated_queries_igt)

        # BioGPT token embeddings for IGT text
        biogpt_embeds = self.biogpt_embed(igt_input_ids)   # [B, L2, 1024]

        # Concatenate visual query embeddings before text embeddings (image-grounded)
        igt_input_embeds = torch.cat([projected_queries, biogpt_embeds], dim=1)  # [B, Q+L2, 1024]

        # Only compute logits over the text portion
        text_logits    = self.lm_head(igt_input_embeds[:, Q:, :])   # [B, L2, vocab]
        shifted_logits = text_logits[:, :-1, :]                      # [B, L2-1, vocab]
        shifted_labels = igt_labels[:, 1:]                           # [B, L2-1]

        loss_igt = F.cross_entropy(
            shifted_logits.reshape(-1, shifted_logits.shape[-1]),
            shifted_labels.reshape(-1),
            ignore_index=-100,
        )

        total_loss = loss_itc + loss_itm + loss_igt
        return total_loss, {"itc": loss_itc.item(), "itm": loss_itm.item(), "igt": loss_igt.item()}

# ── 8d.  PRETRAINING LOOP ────────────────────────────────────

def _prepare_igt_batch(biogpt_tokenizer, reports, max_length, device):
    """
    Tokenize short reports with BioGPT tokenizer for IGT supervision.
    Returns input_ids, attention_mask, and labels (prompt tokens masked).
    Called inside pretrain_qformer per batch.
    """
    enc = biogpt_tokenizer(
        reports,
        padding="max_length",
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    input_ids      = enc["input_ids"].to(device)
    attention_mask = enc["attention_mask"].to(device)
    labels         = input_ids.clone()
    labels[attention_mask == 0] = -100   # mask padding
    return input_ids, attention_mask, labels


def pretrain_qformer(
    pretrain_model,
    loader,
    optimizer,
    epochs,
    device,
    max_grad_norm      = 1.0,
    warmup_ratio       = 0.1,
    save_dir           = "checkpoints",
    early_stopper      = None,
    accumulation_steps = 1,
    igt_max_length     = 128,
    resume_ckpt        = None,
):
 
    from transformers import get_cosine_schedule_with_warmup

    # Support optional validation loader
    if isinstance(loader, (tuple, list)):
        train_loader, val_loader = loader
    else:
        train_loader, val_loader = loader, None

    os.makedirs(save_dir, exist_ok=True)
    scaler = torch.amp.GradScaler("cuda", init_scale=1024)

    total_steps  = (len(train_loader) // accumulation_steps) * epochs
    warmup_steps = max(1, int(total_steps * warmup_ratio))
    scheduler    = get_cosine_schedule_with_warmup(
        optimizer, num_warmup_steps=warmup_steps, num_training_steps=total_steps
    )

    biogpt_tok  = pretrain_model.biogpt_tokenizer
    best_loss   = float("inf")
    start_epoch = 1

    if resume_ckpt is not None and os.path.exists(resume_ckpt):
        ckpt = torch.load(resume_ckpt, map_location="cpu")
        pretrain_model.qformer.load_state_dict(ckpt["qformer"])
        pretrain_model.vision_proj.load_state_dict(ckpt["vision_proj"])
        pretrain_model.igt_proj.load_state_dict(ckpt["igt_proj"])
        optimizer.load_state_dict(ckpt["optimizer"])
        scheduler.load_state_dict(ckpt["scheduler"])
        best_loss   = ckpt["loss"]
        start_epoch = ckpt["epoch"] + 1
        print(f"[pretrain] Resumed from epoch {ckpt['epoch']}  best_loss={best_loss:.4f}")
        print(f"[pretrain] Continuing from epoch {start_epoch} → {epochs}")

    for epoch in range(start_epoch, epochs + 1):
        pretrain_model.train()
        epoch_loss = epoch_itc = epoch_itm = epoch_igt = 0.0
        num_batches = 0

        loop = tqdm(train_loader, desc=f"[pretrain] Epoch {epoch}/{epochs}", leave=False)
        optimizer.zero_grad()

        for i, batch in enumerate(loop):
            images         = batch["images"].to(device)
            image_mask     = batch["image_mask"].to(device)
            text_input_ids = batch["text_input_ids"].to(device)
            text_attn_mask = batch["text_attn_mask"].to(device)

            # FIX 2: decode BERT tokens back to strings, re-tokenize with BioGPT
            raw_texts = pretrain_model.bert_tokenizer.batch_decode(
                text_input_ids, skip_special_tokens=True
            )
            igt_ids, igt_mask, igt_labels = _prepare_igt_batch(
                biogpt_tok, raw_texts, igt_max_length, device
            )

            with torch.amp.autocast("cuda"):
                total_loss, loss_dict = pretrain_model(
                    images, image_mask,
                    text_input_ids, text_attn_mask,
                    igt_ids, igt_mask, igt_labels,
                )
                total_loss = total_loss / accumulation_steps

            scaler.scale(total_loss).backward()

            if (i + 1) % accumulation_steps == 0:
                scaler.unscale_(optimizer)
                nn.utils.clip_grad_norm_(
                    filter(lambda p: p.requires_grad, pretrain_model.parameters()),
                    max_grad_norm,
                )
                scaler.step(optimizer)
                scaler.update()
                optimizer.zero_grad()
                scheduler.step()

                epoch_loss  += total_loss.item() * accumulation_steps
                epoch_itc   += loss_dict["itc"]
                epoch_itm   += loss_dict["itm"]
                epoch_igt   += loss_dict["igt"]
                num_batches += 1

                loop.set_postfix(
                    total=f"{total_loss.item() * accumulation_steps:.4f}",
                    itc=f"{loss_dict['itc']:.4f}",
                    itm=f"{loss_dict['itm']:.4f}",
                    igt=f"{loss_dict['igt']:.4f}",
                    lr=f"{scheduler.get_last_lr()[0]:.2e}",
                )

        mean_train_loss = epoch_loss / max(num_batches, 1)

        # ── Validation pass ───────────────────────────
        if val_loader is not None:
            pretrain_model.eval()
            val_loss_sum, val_n = 0.0, 0
            with torch.no_grad():
                for vbatch in val_loader:
                    vimages     = vbatch["images"].to(device)
                    vimg_mask   = vbatch["image_mask"].to(device)
                    vtxt_ids    = vbatch["text_input_ids"].to(device)
                    vtxt_mask   = vbatch["text_attn_mask"].to(device)
                    vraw        = pretrain_model.bert_tokenizer.batch_decode(
                        vtxt_ids, skip_special_tokens=True
                    )
                    vigt_ids, vigt_mask, vigt_labels = _prepare_igt_batch(
                        biogpt_tok, vraw, igt_max_length, device
                    )
                    with torch.amp.autocast("cuda"):
                        vloss, _ = pretrain_model(
                            vimages, vimg_mask, vtxt_ids, vtxt_mask,
                            vigt_ids, vigt_mask, vigt_labels,
                        )
                    val_loss_sum += vloss.item()
                    val_n        += 1
            mean_val_loss = val_loss_sum / max(val_n, 1)
            stop_loss = mean_val_loss
        else:
            mean_val_loss = None
            stop_loss     = mean_train_loss

        val_str = f"  val={mean_val_loss:.4f}" if mean_val_loss is not None else ""
        tqdm.write(
            f"[pretrain] Epoch {epoch}/{epochs}  "
            f"train={mean_train_loss:.4f}{val_str}  "
            f"ITC={epoch_itc/max(num_batches,1):.4f}  "
            f"ITM={epoch_itm/max(num_batches,1):.4f}  "
            f"IGT={epoch_igt/max(num_batches,1):.4f}  "
            f"lr={scheduler.get_last_lr()[0]:.2e}"
        )

        if stop_loss < best_loss:
            best_loss = stop_loss
            ckpt_path = os.path.join(save_dir, "qformer_pretrain_best.pt")
            torch.save({
                "epoch":       epoch,
                "loss":        best_loss,
                "itc":         epoch_itc / max(num_batches, 1),
                "itm":         epoch_itm / max(num_batches, 1),
                "igt":         epoch_igt / max(num_batches, 1),
                "qformer":     pretrain_model.qformer.state_dict(),
                "vision_proj": pretrain_model.vision_proj.state_dict(),
                "igt_proj":    pretrain_model.igt_proj.state_dict(),   # saved to init model.proj at Stage 1
                "optimizer":   optimizer.state_dict(),
                "scheduler":   scheduler.state_dict(),
            }, ckpt_path)
            tqdm.write(f"  ↳ Best ({best_loss:.4f}) → {ckpt_path}")

        if epoch % 2 == 0:
            torch.save(
                pretrain_model.qformer.state_dict(),
                os.path.join(save_dir, f"qformer_pretrain_epoch{epoch}.pt")
            )

        if early_stopper is not None and early_stopper.step(stop_loss):
            tqdm.write(f"[pretrain] Early stopping at epoch {epoch}.")
            break

    return pretrain_model


def load_pretrained_qformer(base_model: RadBLIPBioGPT, ckpt_path: str):
    """
    Load Stage 0 weights into RadBLIPBioGPT.

    Loads:
      qformer     → base_model.qformer
      vision_proj → base_model.vision_proj
      igt_proj    → base_model.proj   (same shape: 768 → 1024)

    igt_proj was trained during Stage 0 IGT to map Q-Former output into
    BioGPT's embedding space.  base_model.proj has the identical dimensions
    (qformer.config.hidden_size=768 → llm.config.hidden_size=1024), so the
    weights transfer directly.  This means Stage 1 starts with a proj layer
    that already knows how to bridge Q-Former → BioGPT, rather than learning
    it from scratch.
    """
    ckpt = torch.load(ckpt_path, map_location="cpu")
    base_model.qformer.load_state_dict(ckpt["qformer"])
    base_model.vision_proj.load_state_dict(ckpt["vision_proj"])
    base_model.proj.load_state_dict(ckpt["igt_proj"])   # transfer igt_proj → model.proj
    print(f"[LoadQFormer] Loaded pretrained Q-Former + igt_proj from {ckpt_path}")
    print(f"  loss={ckpt['loss']:.4f}  ITC={ckpt['itc']:.4f}  "
          f"ITM={ckpt['itm']:.4f}  IGT={ckpt['igt']:.4f}")
    print(f"  igt_proj → model.proj  (768 → 1024, warm-started)")
    return base_model, ckpt

# ─────────────────────────────────────────────────────────────
# 9.  MAIN
# ─────────────────────────────────────────────────────────────

if __name__ == "__main__":

    # Reduces fragmentation when reserved-but-unallocated memory is large
    os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

    # ── Config ────────────────────────────────────────────────

    CSV_PATH    = "mimic_cxr_aug_train.csv"
    ROOT_DIR    = "/content/official_data_iccv_final"
    BATCH_SIZE  = 4
    MAX_LEN     = 256
    DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"
    NUM_WORKERS = 4 if DEVICE == "cuda" else 0
    SAVE_DIR    = "checkpoints"

    print("Loading dataframe …")
    df_study = load_and_expand_dataframe(CSV_PATH)

    # ── Train/val split ───────────────────────

    val_frac = 0.1
    n_val    = max(1, int(len(df_study) * val_frac))
    df_val   = df_study.sample(n=n_val, random_state=42)
    df_train = df_study.drop(df_val.index).reset_index(drop=True)
    df_val   = df_val.reset_index(drop=True)
    print(f"[Split] train={len(df_train)}  val={len(df_val)}")

    # ── Stage 1 datasets (BioGPT tokenizer) ─────────────────── 

    print("Building Stage-1 datasets …")
    train_dataset = MIMICCXRDataset(df_train, root_dir=ROOT_DIR, max_length=MAX_LEN)
    val_dataset   = MIMICCXRDataset(df_val,   root_dir=ROOT_DIR, max_length=MAX_LEN)

    train_loader = DataLoader(
        train_dataset, batch_size=BATCH_SIZE, shuffle=True,
        collate_fn=collate_fn, num_workers=NUM_WORKERS,
        pin_memory=(DEVICE == "cuda"), drop_last=True,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=BATCH_SIZE, shuffle=False,
        collate_fn=collate_fn, num_workers=NUM_WORKERS,
        pin_memory=(DEVICE == "cuda"), drop_last=False,
    )

    # ── Model ─────────────────────────────────────────────────

    print("Initialising model …")
    model = RadBLIPBioGPT().to(DEVICE)

    print("\n========== STAGE 2 TRAINING ==========")

    CKPT_PATH = "/content/checkpoints/stage2_best.pt"

    # ── 1. Load checkpoint ────────────────────────────────────────
    ckpt = torch.load(CKPT_PATH, map_location=DEVICE)
    # print(f"Resuming from epoch {ckpt['epoch']}  |  loss={ckpt['loss']:.4f}")

    # ── 2. Restore model weights ──────────────────────────────────
    model.load_state_dict(ckpt["model"])
    model.to(DEVICE)

    # ── 3. Recreate optimizer with same param groups ───────────────
    freeze_module(model.vision_encoder)
    unfreeze_module(model.qformer)
    unfreeze_module(model.vision_proj)
    unfreeze_module(model.proj)
    unfreeze_last_n_layers_biogpt(model, n_layers=3)

    qformer_params, llm_params = [], []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        if "llm.biogpt.layers" in name:
            llm_params.append(param)
        else:
            qformer_params.append(param)

    optimizer_stage2 = torch.optim.AdamW([
        {"params": qformer_params, "lr": 1e-5, "weight_decay": 1e-2},
        {"params": llm_params,     "lr": 5e-6, "weight_decay": 1e-2},
    ])


    # ── 4. Restore optimizer state ────────────────────────────────
    optimizer_stage2.load_state_dict(ckpt["optimizer"])

    # ── 5. Resume training ────────────────────────────────────────
    train_stage(
        model, train_loader, optimizer_stage2,
        epochs=10,                  # total epochs, not remaining
        start_epoch= ckpt["epoch"] + 1,
        scheduler_state=None, # ckpt["scheduler"]
        device=DEVICE,
        stage_name="stage2",
        max_grad_norm=0.5,
        warmup_ratio=0.1,
        save_dir=SAVE_DIR,
        early_stopper=EarlyStopping(patience=3),
    )

    print("\nTraining complete.")

